# Simple workflow for running tests on push
name: test our code

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "workflow**"] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  run-tests:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies  
        run: npm i
      # - name: Build SASS
      #   run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run prettier
        run: npx prettier --check .